blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/mallowigi/material-theme-issues/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
